<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Vacant
 *
 * @property $id
 * @property $company
 * @property $position
 * @property $modality
 * @property $salary
 * @property $email_company
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Vacant extends Model
{
    
    static $rules = [
		  'company' => 'required',
		  'position' => 'required',
		  'modality' => 'required',
		  'salary' => 'required',
		  'email_company' => 'required',
      'city' => 'required'
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['company','position','modality','salary','email_company', 'city'];

    
    public function scopePosition($query, $position){

      if (empty($position)) return;
      return $query->where('position', $position);

    }

    public function scopeModality($query, $modality){

      if (empty($modality)) return;
      return $query->where('modality', $modality);

    }
    public function scopeCity($query, $city){

      if (empty($city)) return;
      return $query->where('city', $city);

    }

    public function getCities(){
      return [
        "Bogotá",
        "Timbío",
        "Medellín",
        "Cali",
        "Barranquilla",
        "Cartagena",
        "Palermo",
        "Cúcuta",
        "Soledad",
        "Pereira",
        "Bucaramanga",
        "Valledupar",
        "Ibagué",
        "Villavicencio",
        "Soacha",
        "Santa Marta",
        "Montería",
        "Manizales",
        "Buenaventura",
        "Pasto",
        "Bello",
        "Neiva",
        "Palmira",
        "Zarzal",
        "Armenia",
        "Popayán",
        "Itagüí",
        "Sincelejo",
        "Floridablanca",
        "Envigado",
        "Tuluá",
        "Tunja",
        "Barrancabermeja",
        "Zipaquirá",
        "Dosquebradas",
        "Turbo",
        "Ríohacha",
        "Girón",
        "Florencia",
        "Fusagasugá",
        "Rionegro",
        "Cartago",
        "Pitalito",
        "Quibdó",
        "Girardot",
        "Ciénaga",
        "Duitama",
        "Magangué",
        "Maicao",
        "Apartadó",
        "Uribia",
        "Piedecuesta",
        "Facatativá",
        "Guadalajara de Buga",
        "Santander de Quilichao",
        "Sogamoso",
        "Madrid",
        "Aguachica",
        "Ipiales",
        "Yopal",
        "Arauca",
        "Sabaneta",
        "San Andrés",
        "San José del Guaviare",
        "Leticia",
        "Mitú",
        "Mocoa",
        "Inírida",
        "Puerto Carreño",
        "Chía",
        "Jamundí",
        "Yumbo",
        "Mosquera",
        "Fundación",
        "Ocaña",
        "Montelíbano",
        "Tumaco",
        "Chiquinquirá",
        "Sabanalarga",
        "Chigorodó",
        "Cereté",
        "Funza",
        "Caldas",
        "Los Patios",
        "Tierralta",
        "Arjona",
        "Espinal",
        "Acacías",
        "Copacabana",
        "Santa Rosa de Cabal",
        "La Dorada",
        "San Vicente del Caguán",
        "Corozal",
        "Villa del Rosario",
        "Garzón",
        "Planeta Rica",
        "Necoclí",
        "Manaure",
        "El Carmen de Bolívar",
        "Marinilla",
        "Ciénaga de Oro",
        "Turbaco",
        "Puerto Asís",
        "Riosucio",
        "Plato",
        "Villamaría",
        "San Marcos",
        "Pamplona",
        "Florida",
        "Pradera",
        "Orito",
        "Riosucio",
        "Puerto Boyacá",
        "El Banco",
        "San Gil",
        "Valle del Guamuez",
        "Puerto Libertador",
        "Barbosa",
        "Tame",
        "Lorica",
        "Girardota",
        "San Onofre",
        "El Bagre",
        "Guarne",
        "Baranoa",
        "Chinú",
        "Cimitarra",
        "María la Baja",
        "Samaniego",
        "Agustín Codazzi",
        "Carepa",
        "La Vega",
        "San Andrés de Sotavento",
        "Chaparral",
        "Ayapel",
        "Urrao",
        "Roldanillo",
        "Valencia",
        "Puerto Tejada",
        "Cajicá",
        "San Pelayo",
        "Arboletes",
        "Villeta",
        "Andes",
        "Aguazul",
        "Cumaribo",
        "Miranda",
        "El Charco",
        "Montenegro",
        "Cáceres",
        "Santa Rosa del Sur",
        "Pueblo Nuevo",
        "Tuchín",
        "Yarumal",
        "Arauquita",
        "Guaduas",
        "Segovia",
        "Pie de Pató",
        "La Unión",
        "Cumbal",
        "Aracataca",
        "Túquerres",
        "Acevedo",
        "Villa de San Diego de Ubaté",
        "Líbano",
        "Bosconia",
        "San Juan del Cesar",
        "Puerto Berrío",
        "Tarazá",
        "Cajibío",
        "Sibaté",
        "Sampués",
        "Dibulla",
        "El Bordo",
        "Santa Rosa de Osos",
        "Melgar",
        "Tibú",
        "Dagua",
        "La Macarena",
        "Belalcázar",
        "Tocancipá",
        "Sonsón",
        "San Pablo",
        "San Bernardo del Viento",
        "Guacarí",
        "Santiago de Tolú",
        "Gigante",
        "Quimbaya",
        "Cartagena del Chairá",
        "Yarumal",
        "Fonseca",
        "San Vicente de Chucurí",
        "San Luis de Sincé",
        "Puerto López",
        "Campoalegre",
        "Buenos Aires",
        "Caldono",
        "Quinchía",
        "San Agustín",
        "San Juan Nepomuceno",
        "Majagual",
        "Puerto Rico",
        "San Antero",
        "Corinto",
        "La Virginia",
        "Pivijay",
        "Puebloviejo",
        "Puerto Escondido",
        "Bocas de Satinga",
        "Silvia",
        "El Difícil",
        "Inzá",
        "San Pedro de Urabá",
        "Remedios",
        "Paipa",
        "Galapa",
        "Guachavés",
        "Sitionuevo",
        "Puerto Wilches",
        "Neira",
        "Guamo",
        "Amagá",
        "Chimichagua",
        "Planadas",
        "Tabio",
        "Barbosa",
        "Fresno",
        "Purificación",
        "Flandes",
        "Sopó",
        "Moñitos",
        "Aipe",
        "La Dorada",
        "La Calera",
        "Caicedonia",
        "Hatonuevo",
        "San Carlos",
        "Isnos",
        "Coyaima",
        "Circasia",
        "Guamal",
        "Supía",
        "Argelia",
        "Ciudad Bolívar",
        "San Juan de Urabá",
        "Tauramena",
        "Pueblo Bello",
        "Puerto Colombia",
        "Fortul",
        "Los Córdobas",
        "Morales",
        "San Benito Abad",
        "San Alberto",
        "Balboa",
        "Pensilvania",
        "Buesaco",
        "Paz de Ariporo",
        "Mahates",
        "Istmina",
        "Santa Ana",
        "San Martín",
        "Nechí",
        "Pinillos",
        "Yolombó",
        "Solano",
        "Sandoná",
        "Vistahermosa",
        "Sabanagrande",
        "San José",
        "La Unión",
        "Chocontá",
        "Socorro",
        "Santa Rosa",
        "Villanueva",
        "Algeciras",
        "Calamar",
        "Valdivia",
        "El Retorno",
        "Puerto Guzmán",
        "La Montañita",
        "Donmatías",
        "Cogua",
        "Marsella",
        "Rioblanco",
        "El Zulia",
        "Honda",
        "San José",
        "Canalete",
        "Alcalá",
        "El Paso",
        "Santo Tomás",
        "Teorama",
        "Palmar de Varela",
        "Puerto Concordia",
        "Achí",
        "Curumaní",
        "Guadalupe",
        "Luruaco",
        "Dabeiba",
        "Santa Fe de Antioquia",
        "Buenavista",
        "Amalfi",
        "Manzanares",
        "Sardinata",
        "Mutatá",
        "El Colegio",
        "La Jagua de Ibirico",
        "Natagaima",
        "El Doncello",
        "Repelón",
        "Silvania",
        "Pailitas",
        "Villa de Leyva",
        "Timbiquí",
        "Tiquisio",
        "Taminango",
        "Ginebra",
        "Puerto Triunfo",
        "San Bernardo",
        "San Jacinto",
        "Nueva Granada",
        "Galeras",
        "Santa Bárbara",
        "Villagarzón",
        "Moniquirá",
        "Almaguer",
        "El Paujíl",
        "Aguadas",
        "Montecristo",
        "Suaza",
        "Villapinzón",
        "Fredonia",
        "El Retén",
        "Bugalagrande",
        "Samacá",
        "Ovejas",
        "Sotomayor",
        "Timaná",
        "San Lorenzo",
        "Tenjo",
        "Concordia",
        "Simití",
        "Rovira",
        "Polonuevo",
        "Urumita",
        "La Unión",
        "Tadó",
        "Vélez",
        "Tocaima",
        "Campo de la Cruz",
        "Ponedera",
        "Sabana de Torres",
        "Pelaya",
        "Salgar",
        "Totoró",
        "La Primavera",
        "Guaranda",
        "El Rosal",
        "Suesca",
        "Betulia",
        "Retiro",
        "El Piñón",
        "Anorí",
        "Aquitania",
        "Chivolo",
        "Guasca",
        "Landázuri",
        "Támesis",
        "La Apartada",
        "Obando",
        "Condoto",
        "Anapoima",
        "Sopetrán",
        "Tenerife",
        "Juan de Acosta",
        "Titiribí",
        "Río de Oro",
        "El Carmen de Atrato",
        "Córdoba",
        "Guapí",
        "Jardín",
        "Filandia",
        "Altos del Rosario",
        "Manatí",
        "San Jacinto del Cauca",
        "Rosas",
        "Anolaima",
        "Los Santos",
        "Santa Bárbara de Pinto",
        "Saboyá",
        "Hatillo de Loba",
        "Córdoba",
        "Ebéjico",
        "Curití",
        "Caimito",
        "Oiba",
        "Santa Lucía",
        "Cisneros",
        "Puente Nacional",
        "Candelaria",
        "La Unión",
        "Guayabal",
        "Coveñas",
        "Talaigua Nuevo",
        "El Playón",
        "Agua de Dios",
        "El Águila",
        "Belén de los Andaquíes",
        "El Tarra",
        "Mogotes",
        "Santo Domingo",
        "Tubará",
        "Regidor",
        "Lenguazaque",
        "Charalá",
        "Medina",
        "Granada",
        "Suaita",
        "Margarita",
        "Norosí",
        "Puerto Nariño",
        "Chita",
        "Granada",
        "Pesca",
        "Tibaná",
        "San Zenón",
        "Guatapé",
        "Nuquí",
        "Alvarado",
        "Bojacá",
        "Iles",
        "Zapatoca",
        "Junín",
        "Usiacurí",
        "La Belleza",
        "Muzo",
        "Orocué",
        "Puerres",
        "Aratoca",
        "San Francisco",
        "Uramita",
        "Motavita",
        "Uribe",
        "Pedraza",
        "Puerto Parra",
        "San Luis de Palenque",
        "Paratebueno",
        "Santana",
        "Coromoro",
        "Tarso",
        "Ambalema",
        "Maripí",
        "Simacota",
        "Soatá",
        "Tona",
        "Socha",
        "BoavitVacanta",
        "Salento",
        "Guatavita",
        "Güicán",
        "Cubará",
        "Albania",
        "Tasco",
        "Florián",
        "Heliconia",
        "Albán",
        "Colosó",
        "Sutamarchán",
        "Chitaraque",
        "Zipacón",
        "Villanueva",
        "Chíquiza",
        "Caramanta",
        "Tota",
        "Córdoba",
        "San José de Pare",
        "Arcabuco",
        "El Cocuy",
        "Betulia",
        "Labranzagrande",
        "Juradó",
    ];
  }

}
